version: "3.7"

services:
  inventory-api:
    image: ghcr.io/pokedex-gamba/inventory-manager-api:latest
    ports:
      - "8890:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-inventory:3306/pokemon_inventory_manager
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - USER_INFO_API_URL=http://host.docker.internal:8890
    depends_on:
      - db-inventory
    volumes:
      - ./decoding_key:/decoding_key
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-inventory:
    image: mysql:8.0
    build: ./database
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: pokemon_inventory_manager
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
