version: "3.7"

services:
  gamba-api:
    image: ghcr.io/pokedex-inventory-manager/manager-api:latest-x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8890"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-inventory:3306/pokemon_inventory_manager
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - POKEMON_GAMBA_URL=http://host.docker.internal:8889
    depends_on:
      - db-inventory
    volumes:
      - ./target:/app
      - ./decoding_key:/decoding_key
    command: ["java", "-jar", "/app/app.jar"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-inventory:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: pokemon_inventory_manager
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql-inventory

volumes:
  db_data:
